# Generated by Django 5.1.6 on 2025-02-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('kcpe_marks', models.IntegerField(blank=True, null=True)),
                ('current_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('adm', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('classs', models.CharField(max_length=25)),
                ('stream', models.CharField(max_length=25)),
                ('mistake', models.TextField(default='')),
                ('mistake_1', models.TextField(default='')),
                ('punshmentgiven', models.TextField(default='')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='students_pics/')),
                ('third_mistake', models.TextField(blank=True, null=True)),
                ('blackbook', models.BooleanField(default=False)),
            ],
        ),
    ]
