# Generated by Django 5.1.6 on 2025-02-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('adm', models.IntegerField()),
                ('age', models.IntegerField()),
                ('classs', models.CharField(max_length=25)),
                ('stream', models.CharField(max_length=25)),
                ('mistake', models.TextField(default='')),
                ('punshmentgiven', models.TextField(default='')),
            ],
        ),
    ]
