# Generated by Django 5.1.6 on 2025-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mistake_date',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
