# Generated by Django 5.1.6 on 2025-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_current_grade_student_kcpe_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='punshmentgiven',
            new_name='punishmentgiven',
        ),
        migrations.AddField(
            model_name='student',
            name='correction_given',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='adm',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classs',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(max_length=20),
        ),
    ]
