# Generated by Django 5.1.6 on 2025-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_punshmentgiven_student_punishmentgiven_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='correction_given',
            new_name='punshmentgiven',
        ),
        migrations.RemoveField(
            model_name='student',
            name='punishmentgiven',
        ),
        migrations.AlterField(
            model_name='student',
            name='adm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='classs',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(max_length=25),
        ),
    ]
