# Generated by Django 5.1.6 on 2025-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_correction_given_student_punshmentgiven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mistake_1',
            field=models.TextField(default=''),
        ),
    ]
