# Generated by Django 5.1.6 on 2025-02-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_student_mistake_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adm',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
