# Generated by Django 5.1.6 on 2025-02-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_student_adm'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blackbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='third_mistake',
            field=models.TextField(blank=True, null=True),
        ),
    ]
